version: "3.9"
services:
  url-api:
    image: url-api
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  client:
    image: client
    ports:
      - "8080:8080"
    depends_on:
      - "url-api"
  
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped