version: "3.9"
services:
  client:
    image: client
    ports:
      - "8081:8081"
    depends_on:
      - "server"
  server:
    image: url-shortener-server
    build: .
    command: "npm start"
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    restart: unless-stopped